CREATE TABLE IF NOT EXISTS khachhang (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenkh varchar(30) NOT NULL,
  sdt varchar(15) NOT NULL,
  ngaydk timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS taikhoan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  password varchar(100) NOT NULL
);

INSERT INTO taikhoan (username, password)
VALUES ('tin', '01052006')
ON CONFLICT (username) DO NOTHING;
