CREATE TABLE IF NOT EXISTS khachhang (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenkh varchar(30) NOT NULL,
  sdt varchar(15) NOT NULL,
  ngaydk timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS taikhoan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL,
  password varchar(100) NOT NULL
);

INSERT INTO taikhoan (username, password)
SELECT 'tin', '01052006'
WHERE NOT EXISTS (
  SELECT 1 FROM taikhoan WHERE username = 'tin'
);
