using Npgsql;
using TinMI.Models;

namespace TinMI.Services;

public class MiBookingRepository
{
    private readonly string _connectionString;

    public MiBookingRepository(IConfiguration configuration)
    {
        _connectionString = GetPostgresConnectionString(configuration);
    }

    public async Task AddKhachHangAsync(KhachHang khachHang)
    {
        await EnsureSchemaAsync();

        const string sql = """
            INSERT INTO khachhang (tenkh, sdt, ngaydk)
            VALUES (@tenKh, @sdt, @ngayDk);
            """;

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("tenKh", khachHang.TenKh.Trim());
        command.Parameters.AddWithValue("sdt", khachHang.Sdt.Trim());
        command.Parameters.AddWithValue("ngayDk", khachHang.NgayDK);

        await command.ExecuteNonQueryAsync();
    }

    public async Task DeleteKhachHangAsync(int id)
    {
        await EnsureSchemaAsync();

        const string sql = "DELETE FROM khachhang WHERE id = @id;";

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("id", id);

        await command.ExecuteNonQueryAsync();
    }

    public async Task<IReadOnlyList<KhachHang>> GetKhachHangAsync()
    {
        await EnsureSchemaAsync();

        const string sql = """
            SELECT id, tenkh, sdt, ngaydk
            FROM khachhang
            ORDER BY ngaydk DESC, id DESC;
            """;

        var items = new List<KhachHang>();

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(sql, connection);
        await using var reader = await command.ExecuteReaderAsync();

        while (await reader.ReadAsync())
        {
            items.Add(new KhachHang
            {
                Id = reader.GetInt32(reader.GetOrdinal("id")),
                TenKh = reader.GetString(reader.GetOrdinal("tenkh")),
                Sdt = reader.GetString(reader.GetOrdinal("sdt")),
                NgayDK = reader.GetDateTime(reader.GetOrdinal("ngaydk"))
            });
        }

        return items;
    }

    public async Task<IReadOnlyList<DateTime>> GetBookingTimesByDateAsync(DateTime date)
    {
        await EnsureSchemaAsync();

        const string sql = """
            SELECT ngaydk
            FROM khachhang
            WHERE ngaydk >= @startDate AND ngaydk < @endDate
            ORDER BY ngaydk;
            """;

        var items = new List<DateTime>();

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("startDate", date.Date);
        command.Parameters.AddWithValue("endDate", date.Date.AddDays(1));

        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            items.Add(reader.GetDateTime(reader.GetOrdinal("ngaydk")));
        }

        return items;
    }

    public async Task<TaiKhoan?> FindTaiKhoanAsync(string user, string pass)
    {
        await EnsureSchemaAsync();

        const string sql = """
            SELECT id, username, password
            FROM taikhoan
            WHERE username = @user AND password = @pass
            LIMIT 1;
            """;

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("user", user.Trim());
        command.Parameters.AddWithValue("pass", pass);

        await using var reader = await command.ExecuteReaderAsync();
        if (!await reader.ReadAsync())
        {
            return null;
        }

        return new TaiKhoan
        {
            Id = reader.GetInt32(reader.GetOrdinal("id")),
            User = reader.GetString(reader.GetOrdinal("username")),
            Pass = reader.GetString(reader.GetOrdinal("password"))
        };
    }

    private async Task EnsureSchemaAsync()
    {
        const string sql = """
            CREATE TABLE IF NOT EXISTS khachhang (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenkh varchar(30) NOT NULL,
              sdt varchar(15) NOT NULL,
              ngaydk timestamp NOT NULL
            );

            CREATE TABLE IF NOT EXISTS taikhoan (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              username varchar(50) NOT NULL UNIQUE,
              password varchar(100) NOT NULL
            );

            INSERT INTO taikhoan (username, password)
            VALUES ('tin', '01052006')
            ON CONFLICT (username) DO NOTHING;
            """;

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }

    private static string GetPostgresConnectionString(IConfiguration configuration)
    {
        var configuredConnectionString = configuration.GetConnectionString("DefaultConnection");
        var databaseUrl = Environment.GetEnvironmentVariable("DATABASE_URL");
        var environmentConnectionString = Environment.GetEnvironmentVariable("ConnectionStrings__DefaultConnection");
        var rawConnectionString = !string.IsNullOrWhiteSpace(environmentConnectionString)
            ? environmentConnectionString
            : !string.IsNullOrWhiteSpace(databaseUrl)
                ? databaseUrl
                : configuredConnectionString;

        if (string.IsNullOrWhiteSpace(rawConnectionString))
        {
            throw new InvalidOperationException("Missing PostgreSQL connection string.");
        }

        if (rawConnectionString.StartsWith("postgres://", StringComparison.OrdinalIgnoreCase) ||
            rawConnectionString.StartsWith("postgresql://", StringComparison.OrdinalIgnoreCase))
        {
            return ConvertDatabaseUrl(rawConnectionString);
        }

        return rawConnectionString;
    }

    private static string ConvertDatabaseUrl(string databaseUrl)
    {
        var uri = new Uri(databaseUrl);
        var userInfo = uri.UserInfo.Split(':', 2);
        var username = Uri.UnescapeDataString(userInfo[0]);
        var password = userInfo.Length > 1 ? Uri.UnescapeDataString(userInfo[1]) : string.Empty;
        var database = uri.AbsolutePath.TrimStart('/');

        var builder = new NpgsqlConnectionStringBuilder
        {
            Host = uri.Host,
            Port = uri.Port > 0 ? uri.Port : 5432,
            Database = database,
            Username = username,
            Password = password,
            SslMode = SslMode.Require
        };

        return builder.ConnectionString;
    }
}
